USE db;

CREATE TABLE `vb_userfield` (
  `userid` int(10) unsigned NOT NULL DEFAULT 0,
  `temp` mediumtext DEFAULT NULL,
  `field1` mediumtext DEFAULT NULL,
  `field2` mediumtext DEFAULT NULL,
  `field3` mediumtext DEFAULT NULL,
  `field4` mediumtext DEFAULT NULL,
  `field11` mediumtext NOT NULL,
  `field13` mediumtext NOT NULL,
  `field14` mediumtext NOT NULL,
  `field15` mediumtext NOT NULL,
  `field17` mediumtext NOT NULL,
  `field18` mediumtext NOT NULL,
  `field19` mediumtext NOT NULL,
  `field20` mediumtext NOT NULL,
  `field21` mediumtext NOT NULL,
  `field22` mediumtext NOT NULL,
  PRIMARY KEY (`userid`),
  KEY `field18` (`field18`(255))
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `vb_user` (
  `userid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `usergroupid` smallint(5) unsigned NOT NULL DEFAULT 0,
  `membergroupids` varchar(250) NOT NULL DEFAULT '',
  `displaygroupid` smallint(5) unsigned NOT NULL DEFAULT 0,
  `username` varchar(100) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL DEFAULT '',
  `passworddate` date NOT NULL DEFAULT '1000-01-01',
  `email` varchar(100) NOT NULL DEFAULT '',
  `styleid` smallint(5) unsigned NOT NULL DEFAULT 0,
  `parentemail` varchar(50) NOT NULL DEFAULT '',
  `homepage` varchar(100) NOT NULL DEFAULT '',
  `icq` varchar(20) NOT NULL DEFAULT '',
  `aim` varchar(20) NOT NULL DEFAULT '',
  `yahoo` varchar(32) NOT NULL DEFAULT '',
  `msn` varchar(100) NOT NULL DEFAULT '',
  `skype` varchar(32) NOT NULL DEFAULT '',
  `showvbcode` smallint(5) unsigned NOT NULL DEFAULT 0,
  `showbirthday` smallint(5) unsigned NOT NULL DEFAULT 2,
  `usertitle` varchar(250) NOT NULL DEFAULT '',
  `customtitle` smallint(6) NOT NULL DEFAULT 0,
  `joindate` int(10) unsigned NOT NULL DEFAULT 0,
  `daysprune` smallint(6) NOT NULL DEFAULT 0,
  `lastvisit` int(10) unsigned NOT NULL DEFAULT 0,
  `lastactivity` int(10) unsigned NOT NULL DEFAULT 0,
  `lastpost` int(10) unsigned NOT NULL DEFAULT 0,
  `lastpostid` int(10) unsigned NOT NULL DEFAULT 0,
  `posts` int(10) unsigned NOT NULL DEFAULT 0,
  `reputation` int(11) NOT NULL DEFAULT 10,
  `reputationlevelid` int(10) unsigned NOT NULL DEFAULT 1,
  `timezoneoffset` varchar(4) NOT NULL DEFAULT '',
  `pmpopup` smallint(6) NOT NULL DEFAULT 0,
  `avatarid` smallint(6) NOT NULL DEFAULT 0,
  `avatarrevision` int(10) unsigned NOT NULL DEFAULT 0,
  `profilepicrevision` int(10) unsigned NOT NULL DEFAULT 0,
  `sigpicrevision` int(10) unsigned NOT NULL DEFAULT 0,
  `options` int(10) unsigned NOT NULL DEFAULT 33570831,
  `birthday` varchar(10) NOT NULL DEFAULT '',
  `birthday_search` date NOT NULL DEFAULT '1000-01-01',
  `maxposts` smallint(6) NOT NULL DEFAULT -1,
  `startofweek` smallint(6) NOT NULL DEFAULT 1,
  `ipaddress` varchar(45) NOT NULL DEFAULT '',
  `referrerid` int(10) unsigned NOT NULL DEFAULT 0,
  `languageid` smallint(5) unsigned NOT NULL DEFAULT 0,
  `emailstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `threadedmode` smallint(5) unsigned NOT NULL DEFAULT 0,
  `autosubscribe` smallint(6) NOT NULL DEFAULT -1,
  `pmtotal` smallint(5) unsigned NOT NULL DEFAULT 0,
  `pmunread` smallint(5) unsigned NOT NULL DEFAULT 0,
  `salt` char(30) NOT NULL DEFAULT '',
  `ipoints` int(10) unsigned NOT NULL DEFAULT 0,
  `infractions` int(10) unsigned NOT NULL DEFAULT 0,
  `warnings` int(10) unsigned NOT NULL DEFAULT 0,
  `infractiongroupids` varchar(255) NOT NULL DEFAULT '',
  `infractiongroupid` smallint(5) unsigned NOT NULL DEFAULT 0,
  `adminoptions` int(10) unsigned NOT NULL DEFAULT 0,
  `importuserid` bigint(20) NOT NULL DEFAULT 0,
  `profilevisits` int(10) unsigned NOT NULL DEFAULT 0,
  `friendcount` int(10) unsigned NOT NULL DEFAULT 0,
  `friendreqcount` int(10) unsigned NOT NULL DEFAULT 0,
  `vmunreadcount` int(10) unsigned NOT NULL DEFAULT 0,
  `vmmoderatedcount` int(10) unsigned NOT NULL DEFAULT 0,
  `socgroupinvitecount` int(10) unsigned NOT NULL DEFAULT 0,
  `socgroupreqcount` int(10) unsigned NOT NULL DEFAULT 0,
  `pcunreadcount` int(10) unsigned NOT NULL DEFAULT 0,
  `pcmoderatedcount` int(10) unsigned NOT NULL DEFAULT 0,
  `gmmoderatedcount` int(10) unsigned NOT NULL DEFAULT 0,
  `assetposthash` varchar(32) NOT NULL DEFAULT '',
  `fbuserid` varchar(255) NOT NULL,
  `fbjoindate` int(10) unsigned NOT NULL DEFAULT 0,
  `fbname` varchar(255) NOT NULL,
  `logintype` enum('vb','fb') NOT NULL DEFAULT 'vb',
  `fbaccesstoken` varchar(255) NOT NULL,
  `bloggroupreqcount` int(10) unsigned NOT NULL DEFAULT 0,
  `showblogcss` int(10) unsigned NOT NULL DEFAULT 1,
  `arcadeoptions` int(10) unsigned NOT NULL DEFAULT 1,
  `challengecache` int(10) unsigned NOT NULL,
  `favcache` text NOT NULL,
  `tournamentid_playing` int(10) unsigned NOT NULL,
  `xperience` bigint(20) DEFAULT 1,
  `xperience_done` smallint(6) DEFAULT 0,
  `xperience_level` smallint(6) DEFAULT 1,
  `xperience_levelp` smallint(6) DEFAULT 1,
  `xperience_next_level` bigint(20) DEFAULT 0,
  `xperience_next_level_points` bigint(20) DEFAULT 1,
  `xperience_ppd` float DEFAULT 0,
  `xperience_ppd7` float DEFAULT 0,
  `xperience_ppd30` float DEFAULT 0,
  `xperience_awardt` mediumtext DEFAULT NULL,
  `xperience_achievements` mediumtext DEFAULT NULL,
  `xperience_lastupdate` int(10) DEFAULT 1,
  `xperience_awardcount` smallint(6) DEFAULT 0,
  `xperience_promotioncount` smallint(6) DEFAULT 0,
  `xperience_achievementcount` smallint(6) DEFAULT 0,
  `newrepcount` smallint(5) unsigned NOT NULL DEFAULT 0,
  `panjo_selling` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`userid`),
  KEY `usergroupid` (`usergroupid`),
  KEY `username` (`username`),
  KEY `birthday` (`birthday`,`showbirthday`),
  KEY `birthday_search` (`birthday_search`),
  KEY `importuser_index` (`importuserid`),
  KEY `posts` (`posts`),
  KEY `referrerid` (`referrerid`),
  KEY `fbuserid` (`fbuserid`),
  KEY `email` (`email`),
  KEY `lastactivity` (`lastactivity`)
) ENGINE=InnoDB AUTO_INCREMENT=84639 DEFAULT CHARSET=latin1;

CREATE TABLE `vb_usergroup` (
  `usergroupid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(250) NOT NULL DEFAULT '',
  `usertitle` varchar(100) NOT NULL DEFAULT '',
  `passwordexpires` smallint(5) unsigned NOT NULL DEFAULT 0,
  `passwordhistory` smallint(5) unsigned NOT NULL DEFAULT 0,
  `pmquota` smallint(5) unsigned NOT NULL DEFAULT 0,
  `pmsendmax` smallint(5) unsigned NOT NULL DEFAULT 5,
  `opentag` varchar(100) NOT NULL DEFAULT '',
  `closetag` varchar(100) NOT NULL DEFAULT '',
  `canoverride` smallint(5) unsigned NOT NULL DEFAULT 0,
  `ispublicgroup` smallint(5) unsigned NOT NULL DEFAULT 0,
  `forumpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `pmpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `calendarpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `wolpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `adminpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `genericpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `genericoptions` int(10) unsigned NOT NULL DEFAULT 0,
  `signaturepermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `attachlimit` int(10) unsigned NOT NULL DEFAULT 0,
  `avatarmaxwidth` smallint(5) unsigned NOT NULL DEFAULT 0,
  `avatarmaxheight` smallint(5) unsigned NOT NULL DEFAULT 0,
  `avatarmaxsize` int(10) unsigned NOT NULL DEFAULT 0,
  `profilepicmaxwidth` smallint(5) unsigned NOT NULL DEFAULT 0,
  `profilepicmaxheight` smallint(5) unsigned NOT NULL DEFAULT 0,
  `profilepicmaxsize` int(10) unsigned NOT NULL DEFAULT 0,
  `sigpicmaxwidth` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigpicmaxheight` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigpicmaxsize` int(10) unsigned NOT NULL DEFAULT 0,
  `sigmaximages` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigmaxsizebbcode` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigmaxchars` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigmaxrawchars` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sigmaxlines` smallint(5) unsigned NOT NULL DEFAULT 0,
  `importusergroupid` bigint(20) NOT NULL DEFAULT 0,
  `visitormessagepermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `socialgrouppermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `usercsspermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `albumpermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `albumpicmaxwidth` smallint(5) unsigned NOT NULL DEFAULT 0,
  `albumpicmaxheight` smallint(5) unsigned NOT NULL DEFAULT 0,
  `albummaxpics` int(10) unsigned NOT NULL DEFAULT 0,
  `albummaxsize` int(10) unsigned NOT NULL DEFAULT 0,
  `genericpermissions2` int(10) unsigned NOT NULL DEFAULT 0,
  `pmthrottlequantity` int(10) unsigned NOT NULL DEFAULT 0,
  `groupiconmaxsize` int(10) unsigned NOT NULL DEFAULT 0,
  `maximumsocialgroups` int(10) unsigned NOT NULL DEFAULT 0,
  `vbblog_general_permissions` int(10) unsigned NOT NULL DEFAULT 0,
  `vbblog_entry_permissions` int(10) unsigned NOT NULL DEFAULT 0,
  `vbblog_comment_permissions` int(10) unsigned NOT NULL DEFAULT 0,
  `vbblog_customblocks` int(10) unsigned NOT NULL DEFAULT 0,
  `vbblog_custompages` int(10) unsigned NOT NULL DEFAULT 0,
  `vbcmspermissions` int(10) unsigned NOT NULL DEFAULT 0,
  `arcadepermissions` int(10) unsigned NOT NULL,
  `arcadetourperms` int(10) unsigned NOT NULL,
  `minpoststoplay` int(10) unsigned NOT NULL,
  `minreptoplay` int(10) NOT NULL DEFAULT -1000,
  `minreglengthtoplay` int(10) NOT NULL,
  `sigmaxvideos` smallint(5) unsigned NOT NULL DEFAULT 0,
  `awardpermissions` int(10) unsigned NOT NULL DEFAULT 1,
  `panjo_can_sell` tinyint(1) NOT NULL DEFAULT 1,
  `panjo_transaction_fee` decimal(10,2) DEFAULT NULL,
  `panjo_listing_fee` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`usergroupid`)
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=latin1;